#!/usr/bin/env npx tsx
/**
 * VLR Data Fetcher
 *
 * Fetches player statistics from the vlrggapi and generates a static snapshot
 * file that gets imported into the game.
 *
 * Usage:
 *   npx tsx scripts/fetch-vlr-data.ts
 *
 * Or add to package.json scripts:
 *   "fetch-vlr": "tsx scripts/fetch-vlr-data.ts"
 */

import * as fs from 'fs';
import * as path from 'path';

// VLR API types (duplicated here to avoid import issues with path aliases)
interface VlrPlayerStats {
  player: string;
  org: string;
  agents: string[];
  rounds_played: string;
  rating: string;
  average_combat_score: string;
  kill_deaths: string;
  kill_assists_survived_traded: string;
  average_damage_per_round: string;
  kills_per_round: string;
  assists_per_round: string;
  first_kills_per_round: string;
  first_deaths_per_round: string;
  headshot_percentage: string;
  clutch_success_percentage: string;
}

interface VlrApiResponse {
  data: {
    status: number;
    segments: VlrPlayerStats[];
  };
}

// Configuration
const API_BASE = 'https://vlrggapi.vercel.app';
const REGIONS = ['na', 'eu', 'br', 'ap', 'kr', 'cn'] as const;
const OUTPUT_PATH = path.join(process.cwd(), 'src/data/vlrSnapshot.ts');
const REQUEST_DELAY = 1000; // 1 second between requests to be polite

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
};

function log(message: string, color: keyof typeof colors = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchRegionStats(region: string): Promise<VlrPlayerStats[]> {
  const url = `${API_BASE}/stats?region=${region}&timespan=all`;

  try {
    const response = await fetch(url, {
      headers: { Accept: 'application/json' },
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const json: VlrApiResponse = await response.json();
    return json.data?.segments || [];
  } catch (error) {
    log(`  Failed to fetch ${region}: ${error}`, 'red');
    return [];
  }
}

function generateTypeScriptFile(
  data: Record<string, VlrPlayerStats[]>,
  metadata: { fetchedAt: string; regions: string[]; totalPlayers: number }
): string {
  const jsonData = JSON.stringify(data, null, 2);

  return `// VLR Player Data Snapshot
// Auto-generated by scripts/fetch-vlr-data.ts
// Do not edit manually - re-run the script to update

import type { VlrPlayerStats } from '@/types/vlr';

/**
 * Metadata about when this snapshot was taken
 */
export const VLR_SNAPSHOT_META = {
  fetchedAt: '${metadata.fetchedAt}',
  regions: ${JSON.stringify(metadata.regions)},
  totalPlayers: ${metadata.totalPlayers},
} as const;

/**
 * Static snapshot of VLR player statistics.
 * Keyed by VLR region code (na, eu, br, ap, kr, cn).
 */
export const VLR_PLAYER_STATS: Record<string, VlrPlayerStats[]> = ${jsonData};

/**
 * Get all players from all regions as a flat array.
 */
export function getAllVlrPlayers(): VlrPlayerStats[] {
  return Object.values(VLR_PLAYER_STATS).flat();
}

/**
 * Get players for a specific region.
 */
export function getVlrPlayersByRegion(region: string): VlrPlayerStats[] {
  return VLR_PLAYER_STATS[region] || [];
}
`;
}

async function main() {
  log('\n🎮 VLR Data Fetcher', 'cyan');
  log('==================\n', 'cyan');

  const allData: Record<string, VlrPlayerStats[]> = {};
  let totalPlayers = 0;

  for (const region of REGIONS) {
    log(`Fetching ${region.toUpperCase()}...`, 'yellow');

    const players = await fetchRegionStats(region);
    allData[region] = players;
    totalPlayers += players.length;

    log(`  ✓ Got ${players.length} players`, 'green');

    // Be polite to the API
    if (region !== REGIONS[REGIONS.length - 1]) {
      await sleep(REQUEST_DELAY);
    }
  }

  log(`\nTotal: ${totalPlayers} players across ${REGIONS.length} regions`, 'cyan');

  // Generate the TypeScript file
  const metadata = {
    fetchedAt: new Date().toISOString(),
    regions: [...REGIONS],
    totalPlayers,
  };

  const content = generateTypeScriptFile(allData, metadata);

  // Write to file
  fs.writeFileSync(OUTPUT_PATH, content, 'utf-8');
  log(`\n✓ Written to ${OUTPUT_PATH}`, 'green');

  // Show some sample data
  log('\nSample players:', 'dim');
  const samplePlayers = Object.values(allData)
    .flat()
    .slice(0, 5);

  for (const player of samplePlayers) {
    log(`  ${player.player} (${player.org}) - Rating: ${player.rating}`, 'dim');
  }

  log('\n✅ Done!\n', 'green');
}

main().catch((error) => {
  log(`\n❌ Error: ${error.message}\n`, 'red');
  process.exit(1);
});
